---
language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y <dependency-name>
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
after_success:
  - ./runTests